export const welcomeMessages = [
    "Welcome",
    "Howdy",
    "Welcome back",
    "Hello there",
    "Glad to see you",
    "Hey",
    "Great to have you here",
    "Nice to see you again",
    "It's good to have you back",
    "Hello, friend!",
    "Welcome aboard!",
    "Hope you're having a great day!",
    "You're looking sharp today!",
    "Greetings!",
    "Welcome, we missed you!",
    "Long time no see!",
    "Ahoy, matey!",
    "Hola! Bienvenido!",
    "You made it! Welcome!",
    "Pleased to see you!"
];
